# Generated by Django 3.2.13 on 2022-06-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraper',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
